### ISSUE TITLE
when multiple "Spring boot tests", only the first test is OK with gradle "build" task

### ISSUE THREAD

**Issue by pull-vert** [spring-projects/spring-fu#123]
I followed MongoDB sample app for my step by step Spring boot reactive project, I am currently trying to use functional bean registration with kofu : https://github.com/pull-vert/demo-kotlin/tree/step2.1-functional-bean-registration. I am using a Webflux server.

My tests are OK when launched individually, but when I run gradle 'build' in IntelliJ IDEA I have a stacktrace for the second test (first one is fine) :
```
java.lang.IllegalStateException: Only one server per application is supported
    	at org.springframework.fu.kofu.web.WebFluxServerDsl.register$kofu(WebFluxDsl.kt:180) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
    	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:43) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
    	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:27) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
    	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:45) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
    	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:27) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
    	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:45) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
    	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:27) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
    	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
    	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
    	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.1.0.RELEASE.jar:2.1.0.RELEASE]
    	at org.springframework.fu.kofu.ApplicationDsl.run(ApplicationDsl.kt:73) [spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
    	at org.springframework.fu.kofu.ApplicationDsl.run$default(ApplicationDsl.kt:55) [spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
    	at demo.kotlin.repository.CowRepositoryTest.beforeAll(CowRepositoryTest.kt:32) [test/:na]
```

This is how I configured my 2 "SpringBootTests", following examples :

```kotlin
    private lateinit var context: ConfigurableApplicationContext

    @BeforeAll
    fun beforeAll() {
        context = app.run(profiles = "test")
    }

    @AfterAll
    fun afterAll() {
        context.close()
    }
```

Maybe ```close()``` is not synchronous, so in second test when calling ```app.run()```, first context is not yet closed ?

**Comment by sdeleuze** [comment]
Could you share the repository to allow me to have a look?

**Comment by pull-vert** [comment]
My https://github.com/pull-vert/demo-kotlin repository is public, I just added you as a collaborator on it.

Branch that uses kofu is **step2.1-functional-bean-registration**

Thank you for your time @sdeleuze

**Comment by sdeleuze** [comment]
Running `ApiTests` at class level from IDEA or on command line works fine for me, could you check again?

**Comment by sdeleuze** [comment]
Ok I see, I can reproduce it.

**Comment by sdeleuze** [comment]
@pull-vert Could you please check with latest snapshot that your issue is fixed?

**Comment by pull-vert** [comment]
@sdeleuze I tried at first with a jdk 1.8, there is an error :
```
java.lang.UnsupportedClassVersionError: org/springframework/boot/autoconfigure/data/mongo/MongoDataInitializer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

It seams that  jdk11 is now mandatory for spring-fu, so I configured jdk11 and I still have the Exception raised on the second Spring boot test class execution :
```
java.lang.IllegalStateException: Only one server per application is supported
	at org.springframework.fu.kofu.web.WebFluxServerDsl.register$kofu(WebFluxServerDsl.kt:66) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:42) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:27) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:43) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:27) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:43) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
	at org.springframework.fu.kofu.AbstractDsl.initialize(Dsl.kt:27) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:649) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.springframework.fu.kofu.ApplicationDsl.run(ApplicationDsl.kt:77) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
	at org.springframework.fu.kofu.ApplicationDsl.run$default(ApplicationDsl.kt:59) ~[spring-fu-kofu-0.0.3.BUILD-SNAPSHOT.jar:na]
	at demo.kotlin.web.ApiTest.beforeAll(ApiTest.kt:23) ~[test/:na]
```

**Comment by sdeleuze** [comment]
I have fixed the Java version issue, and indeed the problem still occur with your sample project. I will have a second look.

**Comment by sdeleuze** [comment]
This issues has required a major Kofu and Jafu refactoring to make them stateless, so thanks for raising this. It should be fine with your application now.

**Comment by pull-vert** [comment]
Thanks a lot it works perfectly now !
